// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwTIbR5ftsOYH-5QMgp-LQGXs0yZuovrA',
    appId: '1:960846846662:android:5cbca041b088073dc115c7',
    messagingSenderId: '960846846662',
    projectId: 'cartpuller-customer',
    storageBucket: 'cartpuller-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfyFThczG14_EYAloDjyex5WXbeqDplY',
    appId: '1:960846846662:ios:4f9b8768059b6febc115c7',
    messagingSenderId: '960846846662',
    projectId: 'cartpuller-customer',
    storageBucket: 'cartpuller-customer.appspot.com',
    androidClientId: '960846846662-29hu5h338hg7hatmc44hjd5vg2eqn7km.apps.googleusercontent.com',
    iosClientId: '960846846662-rc43nmvde4omo5tkdvu5a7gnbjtqdbhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeVision',
  );
}
